name: LightHouse
on: [push]
jobs:
  lighouthouse-test:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install and run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          echo "MSG=$(lhci autorun --upload.target=temporary-public-storage | grep -o "https://storage.*html")" >> $GITHUB_ENV
      -name: test env 
        run: |
          echo " ${{ env.MSG }} "
      - name: comment the result link here
        uses: zt4ff/auto-commenter@v2
        with:
          type: custom
          body: |
            This is an example custom message 
