name: LightHouse
env:
  PORT: 3000
on: [push]
jobs:
  lighouthouse-test:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Start the server
        run: |
          yarn install
          yarn start&
      - name: Install and Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          echo "LIGHTHOUSE_URL=$(lhci autorun --upload.target=temporary-public-storage | grep -o "https://storage.*html")" >> $GITHUB_ENV
      - name: Comment Lighthouse Result
        uses: lighouthouse-test: ./.github/actions/commenter/
        with:
          type: custom
          body: |
            Link to Lighthouse Result:
            ${{ env.LIGHTHOUSE_URL }}
